export const data = {
  nav_options: [
    { name: 'Overview', _id: 'overview', location: '/overview' },
    { name: 'Drivers', _id: 'drivers', location: '/drivers' },
    { name: 'Fleet', _id: 'fleet', location: '/fleet' },
    // { name: 'Bus Stops', _id: 'bus-stops', location: '/bus-stops' },
    { name: 'Routes', _id: 'routes', location: '/routes' },
    { name: 'Settings', _id: 'settings', location: '/settings' },
  ],
  drivers: [
    {
      name: 'tatenda bako',
      phone: '0771445411',
      bus: 'AE34',
      route: 'karoi-masvingo',
      status: 'departed',
      _id: 'iam-an-id1',
    },
    {
      name: 'tatenda bako',
      phone: '0771445411',
      bus: 'AE34',
      route: 'karoi-masvingo',
      status: 'departed',
      _id: 'iam-an-id',
    },
  ],
  buses: [
    {
      plate: 'FDT546',
      driver: 'tatenda',
      from: 'harare',
      to: 'masvingo',
      distance_left: '8.7',
      progress: 90,
      _id: 'ccsdiu989m',
    },
    {
      plate: 'WE43KK',
      driver: 'tadiwa',
      from: 'harare',
      to: 'mutare',
      distance_left: '100.7',
      progress: 20,
      _id: 'adsf21',
    },
    {
      plate: 'DSF111',
      driver: 'mike',
      from: 'mbare',
      to: 'chitungwiza',
      distance_left: '18.7',
      progress: 90,
      _id: 'po12123',
    },
    {
      plate: 'ACD332',
      driver: 'sharon',
      from: 'kadoma',
      to: 'chegutu',
      distance_left: '81.7',
      progress: 90,
      _id: 'adiiwww122',
    },
    {
      plate: 'ASD554',
      driver: 'huchi',
      from: 'harare',
      to: 'masvingo',
      distance_left: '33.7',
      progress: 10,
      _id: '12nm09m12',
    },
  
  ],
};
